export const dummyTrips = [
  {
    id: '1',
    destination: 'Ayeduase',
    originStation: 'Tech Junction',
    departureTime: '3 min',
    availableSeats: 4,
    fare: 'GHS 3',
  },
  {
    id: '2',
    destination: 'KNUST Campus',
    originStation: 'Tech Junction',
    departureTime: '6 min',
    availableSeats: 12,
    fare: 'GHS 2',
  },
  {
    id: '3',
    destination: 'Tech Junction',
    originStation: 'Ayeduase',
    departureTime: '2 min',
    availableSeats: 5,
    fare: 'GHS 3',
  },
  {
    id: '4',
    destination: 'Ayeduase',
    originStation: 'Kejetia',
    departureTime: '15 min',
    availableSeats: 0,
    fare: 'GHS 5',
  },
  {
    id: '5',
    destination: 'Tech Junction',
    originStation: 'Bantama',
    departureTime: '8 min',
    availableSeats: 2,
    fare: 'GHS 4',
  },
  {
    id: '6',
    destination: 'Ayeduase',
    originStation: 'KNUST Campus',
    departureTime: '4 min',
    availableSeats: 6,
    fare: 'GHS 2',
  },
];
